provider: ollama #anthropic openai

ollama:
  llm:
    model_name: nemotron-3-super:120b
    base_url: http://localhost:11434/v1
    temperature: 0.2

  mem_llm:
    model_name: nemotron-3-nano:4b
    base_url: http://localhost:11434/v1
    temperature: 0.2

anthropic:
  llm:
    model_name: anthropic:claude-sonnet-4-6
    temperature: 0.2
  
  mem_llm:
    model_name: anthropic:claude-sonnet-4-6
    temperature: 0.2
openai:
  llm:
    model_name: openai:gpt-5.2
    temperature: 0.2
  
  mem_llm:
    model_name: openai:gpt-5.2
    temperature: 0.2