provider: openai #anthropic openai ollama

ollama:
  llm:
    model_name: qwen3-next:80b #  nemotron-3-super:120b
    base_url: http://localhost:11434/v1
    temperature: 0.2

  mem_llm:
    model_name: phi4-mini-reasoning:3.8b
    base_url: http://localhost:11434/v1
    temperature: 0.1

anthropic:
  llm:
    model_name: claude-sonnet-4-6
    temperature: 0.2
  
  mem_llm:
    model_name: claude-sonnet-4-6
    temperature: 0.1
openai:
  llm:
    model_name: gpt-5.4-mini
    temperature: 0.2
  
  mem_llm:
    model_name: gpt-5.4-mini
    temperature: 0.1